// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSPORBTOP_HPP
#define _SLDRSPORBTOP_HPP

#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrSporbTop {
  SLdrSporbTop();
  ~SLdrSporbTop();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
};

inline SLdrSporbTop::SLdrSporbTop() : editorProperties(), patterned(), actorInformation() {
  patterned.health.hI_KnockBackResistance = 2.0f;
  actorInformation.lighting.ambientColor = CColor(1.0f, 1.0f, 1.0f, 1.0f);
  actorInformation.visor.visorFlags = 0x0000000fu;
}

inline SLdrSporbTop::~SLdrSporbTop() {}

#endif
