// Generated by scripts/generate_script_loaders.py. Review before integration.
#ifndef _SLDRSPORBPROJECTILE_HPP
#define _SLDRSPORBPROJECTILE_HPP

#include "Kyoto/SObjectTag.hpp"
#include "Kyoto/Streams/CInputStream.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrActorParameters.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrEditorProperties.hpp"
#include "MetroidPrime/ScriptLoader/Structs/SLdrPatternedAITypedef.hpp"

struct SLdrSporbProjectile {
  SLdrSporbProjectile();
  ~SLdrSporbProjectile();

  SLdrEditorProperties editorProperties; // 0x255a4580
  SLdrPatternedAITypedef patterned; // 0xb3774750
  SLdrActorParameters actorInformation; // 0x7e397fed
  CAssetId ballSpitParticleEffect; // 0x677d4fc2
  CAssetId ballEscapeParticleEffect; // 0xaaff1884
};

inline SLdrSporbProjectile::SLdrSporbProjectile() : editorProperties(), patterned(), actorInformation(), ballSpitParticleEffect(kInvalidAssetId), ballEscapeParticleEffect(kInvalidAssetId) {
  patterned.health.hI_KnockBackResistance = 2.0f;
  actorInformation.lighting.ambientColor = CColor(1.0f, 1.0f, 1.0f, 1.0f);
  actorInformation.visor.visorFlags = 0x0000000fu;
}

inline SLdrSporbProjectile::~SLdrSporbProjectile() {}

#endif
